const Types = {
  LIST_PRODUCTS_REQUEST: "LIST_PRODUCTS_REQUEST",
  LIST_PRODUCTS_REQUEST_SUCCESS: "LIST_PRODUCTS_REQUEST_SUCCESS",
  LIST_PRODUCTS_REQUEST_FAIL: "LIST_PRODUCTS_REQUEST_FAIL",
};

export default Types;
